# Database persistence type.
conductor.db.type=postgres
conductor.queue.type=postgres
conductor.external-payload-storage.type=postgres

# Database connectivity
spring.datasource.url=jdbc:postgresql://postgresdb:5432/postgres
spring.datasource.username=conductor
spring.datasource.password=conductor

# Indexing Properties
conductor.indexing.enabled=true
conductor.indexing.type=postgres
# Required to disable connecting to elasticsearch.
conductor.elasticsearch.version=0

# Load sample kitchen-sink workflow
loadSample=false